/* ═══════════════════════════════════════════════════════════════════
   STOAIX v2 — içerik kaynağı (EN + TR)
   Metinler Claude Design handoff'undaki CONTENT objesinden birebir alındı.
   Tek fark: handoff'ta tüm href değerleri "#" idi; burada gerçek hedefler
   LINKS altında tanımlıdır.
   ═══════════════════════════════════════════════════════════════════ */

export const LINKS = {
  briefing: 'https://calendly.com/ataulufer1/20',
  /* Her iki CTA da aynı takvime gider; ikisi de yeni sekmede açılır. */
  sales: 'https://calendly.com/ataulufer1/20',
  console: '/signup',
  login: 'https://platform.stoaix.com/login',
  /* Footer, uzun kuyruk sayfalarını tek tek listelemek yerine dört hub'a bağlanır:
     sayfa compact kalır, 250 URL'lik kümeye yetki bu hub'lar üzerinden akar. */
  footer: {
    en: [
      ['#specification', '/modules', '#integrations', '#governance'],
      ['/ai-receptionist-dental-clinic-uk', '/ai-receptionist-aesthetic-clinic-uk',
       '/healthcare-clinics', '/healthcare-clinics'],
      ['/about', '/case-studies', '/clinic-resources', '/blog', '/contact'],
    ],
    tr: [
      ['#specification', '/modules', '#integrations', '#governance'],
      ['/dis-klinigi-icin-ai', '/estetik-klinik-icin-ai',
       '/healthcare-clinics', '/healthcare-clinics'],
      ['/about', '/case-studies', '/klinik-kaynaklari', '/blog', '/contact'],
    ],
  },
};

export const CONTENT = {
  en: {
    htmlLang: 'en',
    ogLocale: 'en_GB',
    title: 'STOAIX — The AI sales operating system for clinic groups',
    metaDesc: 'Eight AI agents under your governance: every call answered, every lead contacted in under a minute, every follow-up completed. Demand, sales and loyalty on one revenue ledger.',
    nav: ['Platform', 'Specification', 'Deployment', 'Governance', 'Footprint'],
    brief: 'Request a briefing', sales: 'Talk to sales', explore: 'Explore the console →',
    login: 'Sign in',
    eyebrow: 'The AI sales operating system for clinic groups',
    proof: 'Built on 500+ clinic audits',
    heroBody: 'We operate the layer between your marketing spend and your treatment calendar — eight AI agents under your governance, one revenue ledger, and demand generation run by the same team.',
    tw: [
      'Turn missed leads into booked appointments.',
      'Stop losing leads after the first message.',
      'Follow up with every lead, automatically.',
      'Turn old leads into new opportunities.',
      'Respond faster. Convert more.',
      'Your AI partner for clinic growth.',
      'Never let a valuable lead go cold.',
      'From first contact to booked appointment.',
      'Automate follow-ups. Accelerate growth.',
      'Make every lead count.',
      'More conversations. More appointments. More growth.',
      'Your clinic should never miss an opportunity.',
      'AI-powered communication for modern clinics.',
      'Recover lost opportunities with intelligent follow-up.',
      "Turn your clinic's data into growth.",
    ],
    conTitle: 'Agent performance', conSub: 'Last 30 days · All clinics',
    conActivity: 'Activity', liveConsole: 'Live console',
    conNote: 'Illustrative view of the STOAIX console with sample data.',
    tabs: { ov: 'Overview', cv: 'Conversations', cm: 'Campaigns', cl: 'Calendar' },
    cols: {
      agent: 'Agent', conv: 'Conversations', booked: 'Booked', rate: 'Rate', score: 'Quality score',
      ref: 'Ref', fn: 'Function', bench: 'Benchmark',
      camp: ['Campaign', 'Spend', 'Leads', 'Booked', 'Cost / booking'],
      cal: ['Time', 'Patient', 'Status'],
    },
    metrics: [
      { v: '3.1x', l: 'Lead-to-appointment lift' },
      { v: '-42%', l: 'No-show rate' },
      { v: '2,400+', l: 'Conversations / month' },
      { v: '18 days', l: 'Average payback' },
    ],
    agentRows: [
      { n: 'Reception', c: '1,284', b: '312', r: '24%', s: 92 },
      { n: 'Speed-to-Lead', c: '451', b: '186', r: '41%', s: 96 },
      { n: 'Follow-Up', c: '2,940', b: '204', r: '7%', s: 78 },
      { n: 'Revive', c: '4,110', b: '190', r: '5%', s: 64 },
      { n: 'Scheduler', c: '1,860', b: '148', r: '8%', s: 88 },
    ],
    feed: [
      { t: 'Reception', m: 'Answered inbound call · booked implant consult', s: '12s ago' },
      { t: 'Speed-to-Lead', m: 'Called a new Meta lead in 38s · qualified', s: '41s ago' },
      { t: 'Scheduler', m: 'Filled a cancelled 14:30 slot from the waitlist', s: '1m ago' },
      { t: 'Revive', m: 'Re-engaged a 2023 lead · consultation booked', s: '2m ago' },
      { t: 'Reviews', m: 'Patient left a 5★ Google review', s: '3m ago' },
      { t: 'Follow-Up', m: '7th touch on an open quote · patient replied', s: '4m ago' },
      { t: 'Recall', m: '6-month check-up reminder accepted', s: '5m ago' },
      { t: 'Feedback', m: 'Post-op survey completed · NPS 9', s: '6m ago' },
    ],
    transcript: [
      { w: 'Patient', m: 'Can I get a price for an implant?' },
      { w: 'STOAIX', m: 'Of course. A single implant is £950–£1,250, confirmed after the consultation. Tomorrow 14:30 is free — shall I hold it?' },
      { w: 'Patient', m: 'Yes, please book it.' },
      { w: 'STOAIX', m: 'Booked. Confirmation sent by SMS, with a reminder the day before.' },
    ],
    campaigns: [
      { n: 'Google Ads · Implants', a: '£8,400', b: '96', c: '31', d: '£271' },
      { n: 'Meta · Hair transplant', a: '£5,900', b: '184', c: '42', d: '£140' },
      { n: 'SEO · City pages', a: '£2,100', b: '121', c: '27', d: '£78' },
    ],
    calendar: [
      { t: '09:30', p: 'Implant consult · A. Yılmaz', s: 'Confirmed' },
      { t: '10:15', p: 'Check-up · M. Demir', s: 'Confirmed' },
      { t: '11:00', p: 'Hair transplant call · R. Khan', s: 'Reminder sent' },
      { t: '13:45', p: 'Open slot — filled from waitlist', s: 'New' },
      { t: '14:30', p: 'Implant consult · S. Aydın', s: 'Confirmed' },
      { t: '16:00', p: 'Aesthetic consult · L. Meier', s: 'Awaiting confirmation' },
    ],
    pillars: [
      { h: 'Demand', t: 'Google & Meta campaigns, SEO engine, landing pages — built and optimised by AI, reviewed by our strategists.' },
      { h: 'Sales', t: 'Every call answered, every lead contacted in under a minute, every follow-up completed. No lead goes cold.' },
      { h: 'Loyalty', t: 'Post-treatment surveys, review collection, recall campaigns — the patient base keeps producing revenue.' },
    ],
    specNote: 'Eight agents · one patient record · your escalation rules',
    team: [
      { n: 'Reception', r: 'Inbound', d: 'Answers every call and message, handles questions, books appointments.', m: '24/7' },
      { n: 'Speed-to-Lead', r: 'First contact', d: 'Calls a new enquiry within 60 seconds, qualifies and books.', m: '< 60s' },
      { n: 'Follow-Up', r: 'Nurture', d: 'Runs multi-channel sequences until the patient replies.', m: '7 touches' },
      { n: 'Revive', r: 'Database', d: 'Segments and reactivates dormant lead data with campaigns.', m: '+18% pipeline' },
      { n: 'Scheduler', r: 'Calendar', d: 'Confirms, reminds, reschedules and fills cancelled slots.', m: '-42% no-show' },
      { n: 'Feedback', r: 'Post-care', d: 'Runs satisfaction surveys and escalates issues to your team.', m: 'NPS tracked' },
      { n: 'Reviews', r: 'Reputation', d: 'Routes happy patients to Google and Trustpilot reviews.', m: '3.4x reviews' },
      { n: 'Recall', r: 'Retention', d: 'Brings patients back when their next treatment is due.', m: '+11% repeat' },
    ],
    intTitle: 'Integrated with the systems your clinics already run',
    intSub: 'Two-way sync. No migration, no parallel data entry.',
    stack: ['WhatsApp', 'HubSpot', 'Salesforce', 'Twilio', 'Zapier', 'Make', 'Go High Level', 'Calendly', 'Pipedrive', 'Zoho CRM', 'Google Ads', 'Dentally', 'Pabau', 'Fresha', 'Acuity', 'Dentsoft', 'Komo CRM', 'Google Calendar', 'Slack', 'Instagram DM', 'Telegram', 'Notion', 'Airtable', 'Webhook API'],
    deployTitle: 'Deployment', govTitle: 'Governance',
    deploy: [
      { w: '01', t: 'Audit', d: 'Call recordings, response times, lead sources and CRM hygiene reviewed against 500+ clinic benchmarks.' },
      { w: '02', t: 'Configuration', d: 'Numbers, channels, CRM and PMS connected. Agents trained on treatments, pricing bands and escalation rules.' },
      { w: '03', t: 'Controlled launch', d: 'One channel, one clinic, supervised. Transcripts reviewed daily with your team.' },
      { w: '04', t: 'Scale & governance', d: 'Remaining channels and sites switched on. Monthly performance review with a named account lead.' },
    ],
    governance: [
      { t: 'KVKK & GDPR compliant', d: 'Data processing agreement, regional hosting, full audit trail.' },
      { t: 'Multi-site ready', d: 'Permissions and reporting split by clinic, language and team.' },
      { t: 'Role-based access', d: 'SSO, audit logs and team-level visibility controls.' },
      { t: 'Dedicated onboarding', d: 'A named specialist for setup, training and the first 90 days.' },
    ],
    /* Cevaplar sayfanın kendi bölümlerinden türetildi — yeni iddia içermez.
       Yapay zeka aramalarının alıntılayabilmesi için FAQPage şemasıyla da yayınlanır. */
    faqTitle: 'Questions clinic groups ask',
    faqNote: 'Answered in full on a briefing call',
    faq: [
      { q: 'Is this an AI receptionist?',
        a: 'Reception is one of the eight agents. An AI receptionist answers the call that comes in; STOAIX also runs what happens before and after it — demand generation, a callback within 60 seconds, multi-channel follow-up, dormant lead reactivation, filling cancelled slots, post-treatment surveys and recall.' },
      { q: 'How do you work with our clinic?',
        a: 'As a business partner, not a software subscription. The agents work alongside your front desk rather than replacing it, and hand over on your escalation rules — anything outside the treatments and pricing bands they are trained on goes to your team. Our strategists review the campaigns and a named account lead runs the monthly review with you.' },
      { q: 'Does it work with the CRM and clinic software we already run?',
        a: 'Yes — two-way sync with 24 systems including HubSpot, Salesforce, Dentally, Pabau, Fresha and Google Calendar, plus a webhook API. Nothing is migrated and nobody enters the same data twice.' },
      { q: 'How does it work across multiple sites?',
        a: 'Permissions and reporting are split by clinic, language and team. Each site sees its own pipeline; the group sees one consolidated record.' },
      { q: 'How is KVKK and GDPR compliance handled?',
        a: 'A data processing agreement, regional hosting and a full audit trail. Role-based access with SSO and audit logs controls who can see what.' },
      { q: 'How long does deployment take?',
        a: 'Four stages: audit, configuration, a supervised launch on one channel at one clinic, then scale. Supervised and reversible at every step — nothing is switched on all at once.' },
    ],
    footTitle: 'Footprint', footMeta: '15 countries · 6 languages in production',
    mapAlt: 'World map showing STOAIX deployments across Europe, Türkiye, the Gulf and North America.',
    countries: ['Türkiye', 'United Kingdom', 'Germany', 'Poland', 'Netherlands', 'Italy', 'Spain', 'Romania', 'Azerbaijan', 'Georgia', 'UAE', 'Saudi Arabia', 'Qatar', 'United States', 'Canada'],
    ctaHead: 'Bring us your numbers. We will tell you what they should be.',
    leaders: [{ n: 'Ata Ulufer', r: 'Co-founder & CEO' }, { n: 'Emir Türköz', r: 'Co-founder & CTO' }],
    footerCols: [
      { h: 'Platform', items: ['AI agents', 'Growth', 'Integrations', 'Security'] },
      { h: 'Solutions', items: ['Dental', 'Aesthetics & hair', 'Ophthalmology', 'Multi-site groups'] },
      { h: 'Company', items: ['About', 'Customer stories', 'Resources', 'Blog', 'Contact'] },
    ],
    copyright: '© 2026 STOAIX Ltd. — London, UK',
    skip: 'Skip to main content', menu: 'Menu', close: 'Close',
    themeLabel: 'Theme', langLabel: 'Language', dark: 'Dark', light: 'Light',
  },

  tr: {
    htmlLang: 'tr',
    ogLocale: 'tr_TR',
    title: 'STOAIX — Klinik grupları için yapay zeka satış işletim sistemi',
    metaDesc: 'Sizin yönetişiminiz altında sekiz AI asistan: her arama yanıtlanır, her lead bir dakika içinde aranır, her takip tamamlanır. Talep, satış ve sadakat tek gelir tablosunda.',
    nav: ['Platform', 'AI Asistanlar', 'Devreye alma', 'Yönetişim', 'Sahada'],
    brief: 'Tanışma görüşmesi', sales: 'Satış ekibiyle görüşün', explore: 'Konsolu keşfedin →',
    login: 'Giriş yap',
    eyebrow: 'Klinik grupları için yapay zeka satış işletim sistemi',
    proof: '500+ klinik denetimi üzerine kurulu',
    heroBody: 'Pazarlama bütçenizle tedavi takviminiz arasındaki katmanı biz işletiriz — sizin yönetişiminiz altında sekiz AI asistan, tek bir gelir tablosu ve aynı ekip tarafından yürütülen talep üretimi.',
    tw: [
      "Kaçan lead'leri randevuya dönüştürün.",
      'İlk mesajdan sonra lead kaybetmeyi durdurun.',
      "Her lead'i otomatik olarak takip edin.",
      'Eski leadleri yeni fırsatlara dönüştürün.',
      'Daha hızlı yanıtlayın. Daha fazla dönüştürün.',
      'Kliniğinizin büyümesi için AI ortağınız.',
      "Değerli hiçbir lead'in soğumasına izin vermeyin.",
      'İlk temastan randevuya kadar.',
      'Takip süreçlerini otomatikleştirin. Büyümeyi hızlandırın.',
      "Her lead'i değerli hale getirin.",
      'Daha fazla görüşme. Daha fazla randevu. Daha fazla büyüme.',
      'Kliniğiniz hiçbir fırsatı kaçırmamalı.',
      'Modern klinikler için AI destekli iletişim.',
      'Akıllı takip ile kaybedilen fırsatları geri kazanın.',
      'Kliniğinizin verisini büyümeye dönüştürün.',
    ],
    conTitle: 'AI asistan performansı', conSub: 'Son 30 gün · Tüm klinikler',
    conActivity: 'Aktivite', liveConsole: 'Canlı konsol',
    conNote: 'STOAIX konsolunun örnek verilerle hazırlanmış temsili görünümü.',
    tabs: { ov: 'Genel bakış', cv: 'Görüşmeler', cm: 'Kampanyalar', cl: 'Takvim' },
    cols: {
      agent: 'AI Asistan', conv: 'Görüşme', booked: 'Randevu', rate: 'Oran', score: 'Kalite puanı',
      ref: 'Ref', fn: 'Görev', bench: 'Referans değer',
      camp: ['Kampanya', 'Harcama', 'Lead', 'Randevu', 'Randevu başına'],
      cal: ['Saat', 'Hasta', 'Durum'],
    },
    metrics: [
      { v: '3,1x', l: "Lead'den randevuya artış" },
      { v: '-%42', l: 'Randevuya gelmeme oranı' },
      { v: '2.400+', l: 'Aylık görüşme' },
      { v: '18 gün', l: 'Yatırımın geri dönüş süresi' },
    ],
    agentRows: [
      { n: 'Reception', c: '1.284', b: '312', r: '%24', s: 92 },
      { n: 'Speed-to-Lead', c: '451', b: '186', r: '%41', s: 96 },
      { n: 'Follow-Up', c: '2.940', b: '204', r: '%7', s: 78 },
      { n: 'Revive', c: '4.110', b: '190', r: '%5', s: 64 },
      { n: 'Scheduler', c: '1.860', b: '148', r: '%8', s: 88 },
    ],
    feed: [
      { t: 'Reception', m: 'Gelen arama yanıtlandı · implant konsültasyonu açıldı', s: '12 sn önce' },
      { t: 'Speed-to-Lead', m: "Yeni Meta lead'i 38 saniyede arandı · nitelendi", s: '41 sn önce' },
      { t: 'Scheduler', m: 'İptal olan 14:30 slotu bekleme listesinden dolduruldu', s: '1 dk önce' },
      { t: 'Revive', m: "2023 lead'i yeniden kazanıldı · konsültasyon açıldı", s: '2 dk önce' },
      { t: 'Reviews', m: 'Hasta 5★ Google yorumu bıraktı', s: '3 dk önce' },
      { t: 'Follow-Up', m: 'Açık teklife 7. temas · hasta yanıt verdi', s: '4 dk önce' },
      { t: 'Recall', m: '6 aylık kontrol hatırlatması kabul edildi', s: '5 dk önce' },
      { t: 'Feedback', m: 'Operasyon sonrası anket tamamlandı · NPS 9', s: '6 dk önce' },
    ],
    transcript: [
      { w: 'Hasta', m: 'İmplant için fiyat alabilir miyim?' },
      { w: 'STOAIX', m: 'Elbette. Tek implant 18.500–24.000 TL arasında; muayene sonrası netleşiyor. Yarın 14:30 uygun, ayırayım mı?' },
      { w: 'Hasta', m: 'Uygun, ayırın.' },
      { w: 'STOAIX', m: "Randevunuz oluşturuldu. Onay SMS'i gönderildi, hatırlatma bir gün önce gelecek." },
    ],
    campaigns: [
      { n: 'Google Ads · İmplant', a: '₺142.000', b: '96', c: '31', d: '₺4.580' },
      { n: 'Meta · Saç ekimi', a: '₺98.400', b: '184', c: '42', d: '₺2.340' },
      { n: 'SEO · Şehir sayfaları', a: '₺36.000', b: '121', c: '27', d: '₺1.330' },
    ],
    calendar: [
      { t: '09:30', p: 'İmplant konsültasyonu · A. Yılmaz', s: 'Onaylı' },
      { t: '10:15', p: 'Kontrol · M. Demir', s: 'Onaylı' },
      { t: '11:00', p: 'Saç ekimi görüşmesi · R. Khan', s: 'Hatırlatma gönderildi' },
      { t: '13:45', p: 'Boş slot — bekleme listesinden dolduruldu', s: 'Yeni' },
      { t: '14:30', p: 'İmplant konsültasyonu · S. Aydın', s: 'Onaylı' },
      { t: '16:00', p: 'Estetik konsültasyonu · L. Meier', s: 'Teyit bekliyor' },
    ],
    pillars: [
      { h: 'Talep', t: 'Google ve Meta kampanyaları, SEO motoru, açılış sayfaları — yapay zeka ile kurulur, stratejistlerimiz tarafından denetlenir.' },
      { h: 'Satış', t: 'Her arama yanıtlanır, her lead bir dakika içinde aranır, her takip tamamlanır. Hiçbir lead soğumaz.' },
      { h: 'Sadakat', t: 'Tedavi sonrası anketler, yorum toplama, geri çağırma kampanyaları — hasta tabanı gelir üretmeye devam eder.' },
    ],
    specNote: 'Sekiz AI asistan · tek hasta kaydı · sizin eskalasyon kurallarınız',
    team: [
      { n: 'Reception', r: 'Gelen trafik', d: 'Her aramayı ve mesajı yanıtlar, soruları karşılar, randevu açar.', m: '7/24' },
      { n: 'Speed-to-Lead', r: 'İlk temas', d: 'Yeni talebi 60 saniye içinde arar, niteler ve takvime yazar.', m: '< 60 sn' },
      { n: 'Follow-Up', r: 'Takip', d: 'Hasta yanıt verene kadar çok kanallı takip yürütür.', m: '7 temas' },
      { n: 'Revive', r: 'Veri tabanı', d: "Eski lead datasını segmentler ve kampanyayla yeniden canlandırır.", m: '+%18 pipeline' },
      { n: 'Scheduler', r: 'Takvim', d: 'Teyit alır, hatırlatır, erteler ve iptal olan slotu doldurur.', m: '-%42 gelmeme' },
      { n: 'Feedback', r: 'Tedavi sonrası', d: 'Memnuniyet anketi yapar, sorunları ekibinize eskale eder.', m: 'NPS takibi' },
      { n: 'Reviews', r: 'İtibar', d: 'Memnun hastayı Google ve Trustpilot yorumuna yönlendirir.', m: '3,4x yorum' },
      { n: 'Recall', r: 'Geri kazanım', d: 'Kontrol veya tekrar tedavi zamanı gelen hastayı geri getirir.', m: '+%11 tekrar' },
    ],
    intTitle: 'Kliniklerinizin kullandığı sistemlerle entegre',
    intSub: 'İki yönlü senkron. Taşıma yok, çift veri girişi yok.',
    stack: ['WhatsApp', 'HubSpot', 'Salesforce', 'Twilio', 'Zapier', 'Make', 'Go High Level', 'Calendly', 'Pipedrive', 'Zoho CRM', 'Google Ads', 'Dentally', 'Pabau', 'Fresha', 'Acuity', 'Dentsoft', 'Komo CRM', 'Google Calendar', 'Slack', 'Instagram DM', 'Telegram', 'Notion', 'Airtable', 'Webhook API'],
    deployTitle: 'Devreye alma', govTitle: 'Yönetişim',
    deploy: [
      { w: '01', t: 'Analiz', d: 'Arama kayıtları, yanıt süreleri, lead kaynakları ve CRM hijyeni 500+ klinik referansıyla karşılaştırılır.' },
      { w: '02', t: 'Kurulum', d: 'Numaralar, kanallar, CRM ve PMS bağlanır. AI asistanlar tedavi, fiyat aralığı ve eskalasyon kurallarıyla eğitilir.' },
      { w: '03', t: 'Kontrollü yayın', d: 'Tek kanal, tek klinik, gözetim altında. Transkriptler ekibinizle her gün incelenir.' },
      { w: '04', t: 'Ölçek ve yönetişim', d: 'Kalan kanallar ve şubeler açılır. Atanmış müşteri lideriyle aylık performans toplantısı yapılır.' },
    ],
    governance: [
      { t: 'KVKK ve GDPR uyumlu', d: 'Veri işleme sözleşmesi, bölgesel barındırma, tam kayıt izi.' },
      { t: 'Çok şubeli yapı', d: 'Şube, dil ve ekip bazında yetki ve raporlama ayrımı.' },
      { t: 'Rol bazlı erişim', d: 'SSO, denetim kayıtları ve ekip bazlı görünürlük kontrolü.' },
      { t: 'Devreye alma ekibi', d: 'Kurulum, eğitim ve ilk 90 gün için atanmış uzman.' },
    ],
    faqTitle: 'Klinik gruplarının sorduğu sorular',
    faqNote: 'Tamamı tanışma görüşmesinde',
    faq: [
      { q: 'Bu bir AI resepsiyonist mi?',
        a: 'Reception, sekiz AI asistandan yalnızca biri. AI resepsiyonist gelen aramayı yanıtlar; STOAIX bunun öncesini ve sonrasını da işletir — talep üretimi, 60 saniye içinde geri arama, çok kanallı takip, eski lead canlandırma, iptal olan slotların doldurulması, tedavi sonrası anket ve geri kazanım.' },
      { q: 'Kliniğimizle nasıl çalışıyorsunuz?',
        a: 'Bir yazılım aboneliği gibi değil, iş ortağı gibi. AI asistanlar ön büronuzun yerini almaz, onunla birlikte çalışır ve sizin eskalasyon kurallarınıza göre devreder — eğitildikleri tedavi ve fiyat aralıklarının dışındaki her durum ekibinize gider. Kampanyaları stratejistlerimiz denetler, aylık değerlendirmeyi atanmış müşteri lideriniz sizinle birlikte yürütür.' },
      { q: 'Kullandığımız CRM ve klinik yazılımıyla çalışır mı?',
        a: 'Evet — HubSpot, Salesforce, Dentally, Pabau, Fresha ve Google Calendar dahil 24 sistemle iki yönlü senkron, ayrıca webhook API. Veri taşınmaz, kimse aynı kaydı iki kere girmez.' },
      { q: 'Çok şubeli yapıda nasıl çalışıyor?',
        a: 'Yetki ve raporlama şube, dil ve ekip bazında ayrılır. Her şube kendi hattını görür; grup tek bir birleşik kaydı görür.' },
      { q: 'KVKK ve GDPR uyumu nasıl sağlanıyor?',
        a: 'Veri işleme sözleşmesi, bölgesel barındırma ve tam kayıt izi. SSO ve denetim kayıtlarıyla rol bazlı erişim, kimin neyi görebileceğini belirler.' },
      { q: 'Devreye alma ne kadar sürüyor?',
        a: 'Dört aşama: analiz, kurulum, tek klinikte tek kanalla gözetimli yayın, ardından ölçek. Her adımda denetimli ve geri alınabilir — hiçbir şey tek seferde açılmaz.' },
    ],
    footTitle: 'Sahada', footMeta: '15 ülke · 6 dil sahada',
    mapAlt: 'STOAIX kurulumlarının Avrupa, Türkiye, Körfez ve Kuzey Amerika üzerindeki dağılımını gösteren dünya haritası.',
    countries: ['Türkiye', 'Birleşik Krallık', 'Almanya', 'Polonya', 'Hollanda', 'İtalya', 'İspanya', 'Romanya', 'Azerbaycan', 'Gürcistan', 'BAE', 'Suudi Arabistan', 'Katar', 'ABD', 'Kanada'],
    ctaHead: 'Verilerinizi getirin. Ne olması gerektiğini söyleyelim.',
    leaders: [{ n: 'Ata Ulufer', r: 'Kurucu Ortak & CEO' }, { n: 'Emir Türköz', r: 'Kurucu Ortak & CTO' }],
    footerCols: [
      { h: 'Platform', items: ['AI asistanlar', 'Büyüme', 'Entegrasyonlar', 'Güvenlik'] },
      { h: 'Çözümler', items: ['Diş', 'Estetik ve saç', 'Göz', 'Çok şubeli gruplar'] },
      { h: 'Şirket', items: ['Hakkımızda', 'Müşteri hikâyeleri', 'Kaynaklar', 'Blog', 'İletişim'] },
    ],
    copyright: '© 2026 STOAIX Ltd. — Londra, Birleşik Krallık',
    skip: 'Ana içeriğe geç', menu: 'Menü', close: 'Kapat',
    themeLabel: 'Tema', langLabel: 'Dil', dark: 'Koyu', light: 'Açık',
  },
};

/* Harita üzerindeki şehir noktaları — handoff CITIES dizisiyle birebir */
export const CITIES = [
  { n: 'Istanbul', lat: 41.01, lon: 28.98, hub: true, anchor: 'end', dx: -12, dy: 15 },
  { n: 'Ankara', lat: 39.93, lon: 32.86 },
  { n: 'Izmir', lat: 38.42, lon: 27.14 },
  { n: 'Antalya', lat: 36.90, lon: 30.70 },
  { n: 'London', lat: 51.51, lon: -0.13, hub: true, anchor: 'end', dx: -12 },
  { n: 'Manchester', lat: 53.48, lon: -2.24 },
  { n: 'Berlin', lat: 52.52, lon: 13.40, hub: true },
  { n: 'Munich', lat: 48.14, lon: 11.58 },
  { n: 'Warsaw', lat: 52.23, lon: 21.01 },
  { n: 'Amsterdam', lat: 52.37, lon: 4.90 },
  { n: 'Milan', lat: 45.46, lon: 9.19 },
  { n: 'Madrid', lat: 40.42, lon: -3.70 },
  { n: 'Bucharest', lat: 44.43, lon: 26.10 },
  { n: 'Tbilisi', lat: 41.72, lon: 44.79 },
  { n: 'Baku', lat: 40.41, lon: 49.87, hub: true, dy: -10 },
  { n: 'Dubai', lat: 25.20, lon: 55.27, hub: true },
  { n: 'Riyadh', lat: 24.71, lon: 46.68 },
  { n: 'Doha', lat: 25.29, lon: 51.53 },
  { n: 'New York', lat: 40.71, lon: -74.01, hub: true },
  { n: 'Miami', lat: 25.76, lon: -80.19 },
  { n: 'Los Angeles', lat: 34.05, lon: -118.24 },
  { n: 'Toronto', lat: 43.65, lon: -79.38 },
];
