-- ═══════════════════════════════════════════════════════════
--  005 – Promo codes (pop-up discount system)
-- ═══════════════════════════════════════════════════════════

-- Promo codes generated by the pop-up discount system
CREATE TABLE promo_codes (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code           TEXT NOT NULL UNIQUE,
  first_name     TEXT NOT NULL,
  last_name      TEXT NOT NULL,
  phone          TEXT NOT NULL,
  popup_type     TEXT NOT NULL CHECK (popup_type IN ('timed', 'exit_intent')),
  stripe_promo_id TEXT,
  percent_off    NUMERIC DEFAULT 10,
  expires_at     TIMESTAMPTZ NOT NULL,
  used           BOOLEAN DEFAULT false,
  used_at        TIMESTAMPTZ,
  visitor_id     TEXT,
  ip_address     TEXT,
  created_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_promo_codes_code ON promo_codes (code);
CREATE INDEX idx_promo_codes_visitor ON promo_codes (visitor_id);

-- Kill switch: toggle pop-up without deploy
CREATE TABLE site_config (
  key    TEXT PRIMARY KEY,
  value  JSONB NOT NULL DEFAULT 'true'::jsonb
);
INSERT INTO site_config (key, value) VALUES ('promo_popup_enabled', 'true'::jsonb);

-- Analytics: pop-up event tracking
CREATE TABLE promo_events (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event      TEXT NOT NULL CHECK (event IN ('popup_shown', 'popup_dismissed', 'form_submitted', 'code_copied')),
  popup_type TEXT CHECK (popup_type IN ('timed', 'exit_intent')),
  visitor_id TEXT,
  code       TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_promo_events_event ON promo_events (event);
CREATE INDEX idx_promo_events_date ON promo_events (created_at);
